[project]
name = "conllueditor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "regex>=2024.11.6",
    "selenium>=4.31.0",
    "udapi>=0.4.0",
]
